-- Migration: Add likes functionality (Idempotent Version)
-- Version: 001.1
-- Timestamp: 2026-02-03

-- 1. Create the 'likes' table only if it doesn't exist
CREATE TABLE IF NOT EXISTS likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE (user_id, post_id)
);

-- 2. Add indexes for performance if they don't exist
-- We use DROP INDEX IF EXISTS and CREATE INDEX IF NOT EXISTS to handle potential partial runs
DROP INDEX IF EXISTS idx_likes_user_id;
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes(user_id);
DROP INDEX IF EXISTS idx_likes_post_id;
CREATE INDEX IF NOT EXISTS idx_likes_post_id ON likes(post_id);

-- 3. Enable RLS on the table (this is safe to run multiple times)
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;

-- 4. Drop existing policies before creating them to avoid errors
DROP POLICY IF EXISTS "Public likes are viewable by everyone" ON likes;
DROP POLICY IF EXISTS "Users can insert their own likes" ON likes;
DROP POLICY IF EXISTS "Users can delete their own likes" ON likes;

-- 4.1 Recreate RLS policies for 'likes'
CREATE POLICY "Public likes are viewable by everyone"
ON likes FOR SELECT
USING (true);

CREATE POLICY "Users can insert their own likes"
ON likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes"
ON likes FOR DELETE
USING (auth.uid() = user_id);

-- 5. Add like_count to posts table if it doesn't exist
-- We will handle this carefully as ALTER TABLE ADD COLUMN IF NOT EXISTS doesn't automatically add DEFAULT 0
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'posts' AND column_name = 'like_count') THEN
        ALTER TABLE posts ADD COLUMN like_count INT NOT NULL DEFAULT 0;
    END IF;
END
$$;


-- 6. Drop and recreate the function and trigger to ensure they are up to date
DROP TRIGGER IF EXISTS on_like_change ON likes;
DROP FUNCTION IF EXISTS update_like_count();

CREATE OR REPLACE FUNCTION update_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE posts
    SET like_count = like_count + 1
    WHERE id = NEW.post_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE posts
    SET like_count = like_count - 1
    WHERE id = OLD.post_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_like_change
AFTER INSERT OR DELETE ON likes
FOR EACH ROW
EXECUTE FUNCTION update_like_count();
