-- Migration: Add likes functionality
-- Version: 001
-- Timestamp: 2026-02-03

-- 1. Create the 'likes' table
CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,

  -- A user can only like a post once
  UNIQUE (user_id, post_id)
);

-- 2. Add indexes for performance
CREATE INDEX idx_likes_user_id ON likes(user_id);
CREATE INDEX idx_likes_post_id ON likes(post_id);

-- 3. Enable RLS on the new table
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for 'likes'

-- 4.1 Anyone can view likes.
CREATE POLICY "Public likes are viewable by everyone"
ON likes FOR SELECT
USING (true);

-- 4.2 Authenticated users can insert their own like.
CREATE POLICY "Users can insert their own likes"
ON likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4.3 Users can delete their own like (unlike).
CREATE POLICY "Users can delete their own likes"
ON likes FOR DELETE
USING (auth.uid() = user_id);

-- 5. Add like_count to posts table for denormalization and performance
-- This avoids counting likes on every post load.
ALTER TABLE posts
ADD COLUMN like_count INT NOT NULL DEFAULT 0;

-- 6. Create a function to update the like count
CREATE OR REPLACE FUNCTION update_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE posts
    SET like_count = like_count + 1
    WHERE id = NEW.post_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE posts
    SET like_count = like_count - 1
    WHERE id = OLD.post_id;
  END IF;
  RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$$ LANGUAGE plpgsql;

-- 7. Create a trigger to automatically update the like count
CREATE TRIGGER on_like_change
AFTER INSERT OR DELETE ON likes
FOR EACH ROW
EXECUTE FUNCTION update_like_count();
