-- Migration: Add comment likes functionality
-- Version: 002
-- Timestamp: 2026-02-03

-- 1. Create the 'comment_likes' table
CREATE TABLE comment_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  comment_id UUID REFERENCES comments(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,

  -- A user can only like a comment once
  UNIQUE (user_id, comment_id)
);

-- 2. Add indexes for performance
CREATE INDEX idx_comment_likes_user_id ON comment_likes(user_id);
CREATE INDEX idx_comment_likes_comment_id ON comment_likes(comment_id);

-- 3. Enable RLS on the new table
ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for 'comment_likes'

-- 4.1 Anyone can view likes.
CREATE POLICY "Public comment likes are viewable by everyone"
ON comment_likes FOR SELECT
USING (true);

-- 4.2 Authenticated users can insert their own like.
CREATE POLICY "Users can insert their own comment likes"
ON comment_likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4.3 Users can delete their own like (unlike).
CREATE POLICY "Users can delete their own comment likes"
ON comment_likes FOR DELETE
USING (auth.uid() = user_id);

-- 5. Add like_count to comments table
ALTER TABLE comments
ADD COLUMN like_count INT NOT NULL DEFAULT 0;

-- 6. Create a function to update the comment like count
CREATE OR REPLACE FUNCTION update_comment_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE comments
    SET like_count = like_count + 1
    WHERE id = NEW.comment_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE comments
    SET like_count = like_count - 1
    WHERE id = OLD.comment_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 7. Create a trigger to automatically update the comment like count
CREATE TRIGGER on_comment_like_change
AFTER INSERT OR DELETE ON comment_likes
FOR EACH ROW
EXECUTE FUNCTION update_comment_like_count();
