-- Migration: Add comment likes functionality (Idempotent Version)
-- Version: 002.1
-- Timestamp: 2026-02-03

-- 1. Create the 'comment_likes' table only if it doesn't exist
CREATE TABLE IF NOT EXISTS comment_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  comment_id UUID REFERENCES comments(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE (user_id, comment_id)
);

-- 2. Add indexes for performance if they don't exist
-- We use DROP INDEX IF EXISTS and CREATE INDEX IF NOT EXISTS to handle potential partial runs
DROP INDEX IF EXISTS idx_comment_likes_user_id;
CREATE INDEX IF NOT EXISTS idx_comment_likes_user_id ON comment_likes(user_id);
DROP INDEX IF EXISTS idx_comment_likes_comment_id;
CREATE INDEX IF NOT EXISTS idx_comment_likes_comment_id ON comment_likes(comment_id);

-- 3. Enable RLS on the new table (this is safe to run multiple times)
ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY;

-- 4. Drop existing policies before creating them to avoid errors
DROP POLICY IF EXISTS "Public comment likes are viewable by everyone" ON comment_likes;
DROP POLICY IF EXISTS "Users can insert their own comment likes" ON comment_likes;
DROP POLICY IF EXISTS "Users can delete their own comment likes" ON comment_likes;

-- 4.1 Recreate RLS policies for 'comment_likes'
CREATE POLICY "Public comment likes are viewable by everyone"
ON comment_likes FOR SELECT
USING (true);

CREATE POLICY "Users can insert their own comment likes"
ON comment_likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comment likes"
ON comment_likes FOR DELETE
USING (auth.uid() = user_id);

-- 5. Add like_count to comments table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'comments' AND column_name = 'like_count') THEN
        ALTER TABLE comments ADD COLUMN like_count INT NOT NULL DEFAULT 0;
    END IF;
END
$$;

-- 6. Drop and recreate the function and trigger to ensure they are up to date
DROP TRIGGER IF EXISTS on_comment_like_change ON comment_likes;
DROP FUNCTION IF EXISTS update_comment_like_count();

CREATE OR REPLACE FUNCTION update_comment_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE comments
    SET like_count = like_count + 1
    WHERE id = NEW.comment_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE comments
    SET like_count = like_count - 1
    WHERE id = OLD.comment_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_comment_like_change
AFTER INSERT OR DELETE ON comment_likes
FOR EACH ROW
EXECUTE FUNCTION update_comment_like_count();
