-- Migration: Add comment likes functionality
-- Version: 003
-- Timestamp: 2026-02-10
-- Idempotent: Yes (using IF NOT EXISTS)

-- 1. 创建 comment_likes 表
CREATE TABLE IF NOT EXISTS comment_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  comment_id UUID REFERENCES comments(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  
  -- 一个用户只能对一条评论点赞一次
  UNIQUE (user_id, comment_id)
);

-- 2. 创建其进索引
CREATE INDEX IF NOT EXISTS idx_comment_likes_user_id ON comment_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_comment_id ON comment_likes(comment_id);

-- 3. 为 comments 表添加 like_count 字段（如果不存在）
ALTER TABLE comments
ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;

-- 4. 启用 RLS
ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY;

-- 5. 删除旧策略（如果存在）
DROP POLICY IF EXISTS "Public comment likes are viewable by everyone" ON comment_likes;
DROP POLICY IF EXISTS "Users can insert their own comment likes" ON comment_likes;
DROP POLICY IF EXISTS "Users can delete their own comment likes" ON comment_likes;

-- 6. 创建 RLS 策略

-- 6.1 所有人可以查看点赞
CREATE POLICY "Public comment likes are viewable by everyone"
ON comment_likes FOR SELECT
USING (true);

-- 6.2 认证用户可以点赞
CREATE POLICY "Users can insert their own comment likes"
ON comment_likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 6.3 用户可以取消自己的点赞
CREATE POLICY "Users can delete their own comment likes"
ON comment_likes FOR DELETE
USING (auth.uid() = user_id);

-- 7. 创建自动更新点赞计数的函数
CREATE OR REPLACE FUNCTION update_comment_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE comments
    SET like_count = like_count + 1
    WHERE id = NEW.comment_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE comments
    SET like_count = like_count - 1
    WHERE id = OLD.comment_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 8. 删除旧 trigger（如果存在）
DROP TRIGGER IF EXISTS on_comment_like_change ON comment_likes;

-- 9. 创建触发器
CREATE TRIGGER on_comment_like_change
AFTER INSERT OR DELETE ON comment_likes
FOR EACH ROW
EXECUTE FUNCTION update_comment_like_count();
