-- Migration: Add follows (user relationship) functionality
-- Version: 004
-- Timestamp: 2026-02-10
-- Idempotent: Yes (using IF NOT EXISTS)

-- 1. 创建 follows 表
CREATE TABLE IF NOT EXISTS follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  following_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  
  -- 一个用户对另一个用户只能关注一次
  UNIQUE (follower_id, following_id),
  
  -- 防止自己关注自己
  CHECK (follower_id != following_id)
);

-- 2. 创建索引
CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following_id ON follows(following_id);

-- 3. 为 users 表添加计数字段（如果不存在）
ALTER TABLE users
ADD COLUMN IF NOT EXISTS follower_count INT NOT NULL DEFAULT 0;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS following_count INT NOT NULL DEFAULT 0;

-- 4. 启用 RLS
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;

-- 5. 删除旧策略（如果存在）
DROP POLICY IF EXISTS "Public follows are viewable by everyone" ON follows;
DROP POLICY IF EXISTS "Users can follow others" ON follows;
DROP POLICY IF EXISTS "Users can unfollow" ON follows;

-- 6. 创建 RLS 策略

-- 6.1 所有人可以查看关注关系
CREATE POLICY "Public follows are viewable by everyone"
ON follows FOR SELECT
USING (true);

-- 6.2 认证用户可以关注其他人
CREATE POLICY "Users can follow others"
ON follows FOR INSERT
WITH CHECK (auth.uid() = follower_id);

-- 6.3 用户可以取消关注
CREATE POLICY "Users can unfollow"
ON follows FOR DELETE
USING (auth.uid() = follower_id);

-- 7. 创建自动更新关注计数的函数
CREATE OR REPLACE FUNCTION update_follow_counts()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    -- 被关注者的粉丝数 +1
    UPDATE users
    SET follower_count = follower_count + 1
    WHERE id = NEW.following_id;
    
    -- 关注者的关注数 +1
    UPDATE users
    SET following_count = following_count + 1
    WHERE id = NEW.follower_id;
    
  ELSIF (TG_OP = 'DELETE') THEN
    -- 被关注者的粉丝数 -1
    UPDATE users
    SET follower_count = follower_count - 1
    WHERE id = OLD.following_id;
    
    -- 关注者的关注数 -1
    UPDATE users
    SET following_count = following_count - 1
    WHERE id = OLD.follower_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 8. 删除旧 trigger（如果存在）
DROP TRIGGER IF EXISTS on_follow_change ON follows;

-- 9. 创建触发器
CREATE TRIGGER on_follow_change
AFTER INSERT OR DELETE ON follows
FOR EACH ROW
EXECUTE FUNCTION update_follow_counts();
